package model;
// Generated 07/03/2016 05:45:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamentos generated by hbm2java
 */
public class Departamentos  implements java.io.Serializable {


     private Integer iddepartamento;
     private String departamento;
     private Set provinciases = new HashSet(0);

    public Departamentos() {
    }

	
    public Departamentos(String departamento) {
        this.departamento = departamento;
    }
    public Departamentos(String departamento, Set provinciases) {
       this.departamento = departamento;
       this.provinciases = provinciases;
    }
   
    public Integer getIddepartamento() {
        return this.iddepartamento;
    }
    
    public void setIddepartamento(Integer iddepartamento) {
        this.iddepartamento = iddepartamento;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    public Set getProvinciases() {
        return this.provinciases;
    }
    
    public void setProvinciases(Set provinciases) {
        this.provinciases = provinciases;
    }




}


